### ISSUE TITLE
Stuck generating codegen headers

### ISSUE THREAD

**Issue by ArtemisE1Tara** [phaze-the-dumb/codegen-browser-app#1]
![image](https://user-images.githubusercontent.com/87865667/211214959-26b9d5e4-703b-4f5a-8f61-e59d683f9fee.png)

**Comment by phaze-the-dumb** [comment]
didn't have the correct version of dotnet installed 🤦

**Comment by phaze-the-dumb** [comment]
Just to be clear it does say now
![](https://i.phazed.xyz/?Xf47G1b-9EI*g)
